@url = http://127.0.0.1:8080/tarefas
GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "id" : 0,
    "descricao" : "Estudar para prova"
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "id" : 0,
    "descricao" : "Estudar para prova - Modificado"
}

###
DELETE {{url}}/1